# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.12.0
        
      - uses: actions/checkout@v4
      
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      - name: Generate adapters
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
            
